---
title: "Benchmarking response diversity project"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

Response diversity is a component of biodiversity that should predict community and ecosystem stability. For example, a community composed of species that among them have high response diversity should have greater temporal stability of total biomass than a community with low response diversity. Hence, the prediction is of a positive relationship between response diversity and community/ecosystem stability. Furthermore, a measure of response diversity that has a tighter relationship (higher r-squared) with community/ecosystem stability would be preferable to one with a looser relationship. The aim of this project is to assemble tests of this prediction across a range of studies, and if sufficient number of studies are available, to test what features of response diversity measures, of ecosystem type, of organisms, and of measures of stability (and perhaps other features) explain variation in the predictive power of response diversity for community and ecosystem stability.

The project aims to standardise and document methods, so that comparisons can be as valid and clear as possible. Therefore, quite some effort needs to be put into design of individual studies, organisation of data and processing, and each individual study needs to be carefully inserted into the provided analysis framework.

**The benchmarking relies upon:**

* a collection of individual studies. These are listed in the file `overall/data/study_metadata.csv`.
* a collection of metrics of concepts such as community stability and response diversity. These are listed in the file `overall/data/metrics_metadata.csv`

[The content and structure of the two datasets are described here.](./docs/data_requirements.html)

**For each individual study:**

* Data must be carefully processed and arranged in a set of three or four datasets (traits, environment, composition, and community). [The content and structure of these datasets are described here.](./docs/data_requirements.html).

* The data in the three or four datasets must be processed to produce a single dataset containing information about the stability and response diversity of each community. [The content and structure of this datasets are described here.](./docs/data_requirements.html).

[**To be done: Results within and across studies** are here.](link to be added)
